spring.application.name=ticketbooking

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:ticketdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate ORM Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORS Configuration
cors.allowed-origins=http://localhost:5173,http://localhost:5174,https://ticket-booking-fawn-alpha.vercel.app
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ulliyadhidya6002@gmail.com
spring.mail.password=kgmnckkngbbmxpnk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true